apiVersion: v1
kind: Service
metadata:
  name: jenkins-web-interface
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30020
  selector:
    app: jenkins
