apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: job
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 700Mi
  selector:
    matchLabels:
      pv: "jenkins-jobs"

