apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-ui-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: "sonar-ui-data"

